# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.6.0
    hooks:
      # Run the linter.
      - id: ruff
        args: [--fix]
      # Run the formatter.
      - id: ruff-format
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      # Checks for trailing whitespace.
      - id: trailing-whitespace
      # Checks that files end with a newline.
      - id: end-of-file-fixer
      # Checks for files that would conflict with git's case-insensitive file system.
      - id: check-case-conflict
      # Checks for added large files.
      - id: check-added-large-files
