"""Prove that dynavec auto-generates the AWS resources for an index.

Provisions an index, then uses raw boto3 describe/get calls to confirm the
DynamoDB table, the S3 vector bucket, and the vector index actually exist in
your account — and prints their key properties.

Run
---
    python examples/verify_provisioning.py                 # create + verify
    python examples/verify_provisioning.py --cleanup       # ...then delete them

Requires AWS credentials with s3vectors + dynamodb permissions.
"""

from __future__ import annotations

import argparse
import os

import boto3

from dynavec import Dynavec, DynavecConfig

REGION = os.environ.get("AWS_REGION", "us-east-1")
BUCKET = "dynavec-verify-demo"
INDEX = "verify-index"
TABLE = "dynavec_verify_demo"
DIM = 1536


def _ok(label, detail=""):
    print(f"  [OK] {label}" + (f"  ->  {detail}" if detail else ""))


def verify() -> None:
    cfg = DynavecConfig(
        vector_bucket=BUCKET, index=INDEX, table=TABLE,
        dimension=DIM, distance_metric="cosine", region=REGION,
        auto_provision=True,
    )
    print(f"Provisioning index {INDEX!r} in {REGION} ...")
    Dynavec(cfg)  # auto_provision runs on construction
    print("Provision call returned. Verifying via boto3 ...\n")

    s3v = boto3.client("s3vectors", region_name=REGION)
    ddb = boto3.client("dynamodb", region_name=REGION)

    print("S3 Vectors bucket:")
    b = s3v.get_vector_bucket(vectorBucketName=BUCKET)
    bucket = b.get("vectorBucket", b)
    _ok("vector bucket exists", bucket.get("vectorBucketName", BUCKET))

    print("S3 Vectors index:")
    ix = s3v.get_index(vectorBucketName=BUCKET, indexName=INDEX)
    index = ix.get("index", ix)
    _ok("index exists", index.get("indexName", INDEX))
    _ok("dimension", str(index.get("dimension", "?")))
    _ok("distanceMetric", str(index.get("distanceMetric", "?")))
    _ok("dataType", str(index.get("dataType", "?")))

    print("DynamoDB table:")
    t = ddb.describe_table(TableName=TABLE)["Table"]
    _ok("table status", t["TableStatus"])
    _ok("key schema", str([(k["AttributeName"], k["KeyType"]) for k in t["KeySchema"]]))
    _ok("billing mode", t.get("BillingModeSummary", {}).get("BillingMode", "?"))

    print("\nAll three resources were auto-generated by dynavec. ✅")


def cleanup() -> None:
    s3v = boto3.client("s3vectors", region_name=REGION)
    ddb = boto3.client("dynamodb", region_name=REGION)
    print("Cleaning up ...")
    try:
        s3v.delete_index(vectorBucketName=BUCKET, indexName=INDEX)
        _ok("deleted index", INDEX)
    except Exception as e:  # noqa: BLE001
        print(f"  index delete: {e}")
    try:
        s3v.delete_vector_bucket(vectorBucketName=BUCKET)
        _ok("deleted bucket", BUCKET)
    except Exception as e:  # noqa: BLE001
        print(f"  bucket delete: {e}")
    try:
        ddb.delete_table(TableName=TABLE)
        _ok("deleting table", TABLE)
    except Exception as e:  # noqa: BLE001
        print(f"  table delete: {e}")


if __name__ == "__main__":
    p = argparse.ArgumentParser()
    p.add_argument("--cleanup", action="store_true", help="delete the resources after verifying")
    args = p.parse_args()
    verify()
    if args.cleanup:
        print()
        cleanup()
